#!/bin/bash

killall inotifywait
log_file="$HOME"/.local/share/ansoncg/state_watcher/state.log

# Video thumbnails
ansoncg_thumbnail_handler --notify

# Recursive. ~/.config
inotifywait \
	-e close_write \
	-e create \
	-e delete \
	-e move \
	--format "%T | %w%f | %e%n" \
	--no-newline \
	--timefmt "%c" \
	-Prm \
	~/.config \
	--exclude \
	"fish_history|ranger/bookmarks|ranger/history|mpd" \
	-o "$log_file" &

# Non Recursive. ~, ~/.local/share
inotifywait \
	-e close_write \
	-e create \
	-e delete \
	-e move \
	--format "%T | %w%f | %e%n" \
	--no-newline \
	--timefmt "%c" \
	-Pm \
	/home/anderson \
	~/.local/share \
	--exclude \
	"bash_history|python_history|state.log" \
	-o "$log_file" &
