#!/bin/bash

info=$(ansoncg_bluetooth -i k380 | grep "Connected: yes")
while [ -z "$info" ]; do
    ansoncg_bluetooth -c jbl
    sleep 3
    info=$(ansoncg_bluetooth -i k380 | grep "Connected: yes")
done

notify-send "Bluetooth" "Keyboard connected"
solaar config k380 Fn-swap false > /dev/null 2>&1 &
