#!/bin/bash

# Dependencies
# fzf
# jq/jaq

## Variables ---

alias_path="$HOME/.config/ansoncg/sway_output/alias.json"


## List information ---

get_alias_from_output() {
	jaq -rc ".[] | select(.output==\"$1\") | .alias" <"$alias_path"
}

get_output_from_alias() {
	jaq -rc ".[] | select(.alias==\"$1\") | .output" <"$alias_path"
}

list_current_modes() {
	while read -r current_width; do
		read -r current_height
		read -r current_refresh
		read -r current_ratio
		current_refresh=${current_refresh:0:-3}.${current_refresh: -3}Hz
		printf "%sx%s@%s %s\n" "$current_width" "$current_height" "$current_refresh" "$current_ratio"

	done < <(swaymsg -t get_outputs | jaq -rc '(.[].current_mode | .width, .height, .refresh, .picture_aspect_ratio)')
}

list_alias() {
	jaq -rc '.[].alias' <"$alias_path"
}

list_outputs() {
	swaymsg -t get_outputs | jaq -r '.[].name'
}

list_operations() {
	printf "\
List
Mode
Rotate
Scale
Toggle
"
}

list_scale_factor() {
	printf "\
1
1.3
1.5
1.7
2"
}

list_rotations() {
	printf "\
normal
90
180
270
flipped
flipped-90
flipped-180
flipped-270"
}

list_outputs_with_alias() {
	while read -r output; do
		alias=$(get_alias_from_output "$output")
		printf "%-10s | %-10s\n" "$output" "$alias"
	done < <(list_outputs)
}

list_outputs_info() {
	echo "|------------|------------|-------|-----------------------|-------|"
	printf "| %-10s | %-10s | %-5s | %-21s | %-5s |\n" "Name" "Alias" "Scale" "Mode" "Power"
	echo "|------------|------------|-------|-----------------------|-------|"
	while read -r output_name; do
		read -r current_power
		alias=$(get_alias_from_output "$output_name")

		if [ "$current_power" == true ]; then
			read -r current_scale
			read -r current_width
			read -r current_height
			read -r current_refresh
			current_power="On"
			current_refresh=${current_refresh:0:-3}.${current_refresh: -3}Hz
		else
			current_scale=0
			current_width=0
			current_height=0
			current_refresh=0
			current_power="Off"
		fi

		printf "| %-10s | %-10s | %-5s | %4sx%-4s @ %-9s | %-5s |\n" \
			"$output_name" "$alias" "$current_scale" "$current_width" "$current_height" "$current_refresh" "$current_power"

	done < <(swaymsg -t get_outputs |
		jaq -rc \
			'(.[] |
            (.name),
            (.power),
            (select(.power==true) |
                (.scale),
                (.current_mode | .width, .height, .refresh)))')

	echo "|------------|------------|-------|-----------------------|-------|"
}

list_modes() {
	while read -r current_width; do
		read -r current_height
		read -r current_refresh
		read -r current_ratio
		current_refresh=${current_refresh:0:-3}.${current_refresh: -3}Hz
		printf ">>%sx%s@%s<< %s\n" "$current_width" "$current_height" "$current_refresh" "$current_ratio"

		read -r modes_len
		for _ in $(seq 1 "$modes_len"); do
			read -r mode_width
			read -r mode_height
			read -r mode_refresh
			read -r mode_ratio
			mode_refresh=${mode_refresh:0:-3}.${mode_refresh: -3}Hz
			printf "%sx%s@%s %s\n" "$mode_width" "$mode_height" "$mode_refresh" "$mode_ratio"
		done
	done < <(swaymsg -t get_outputs |
		jaq -rc \
			"(.[] 
                | select(.name==\"$choice_output\") 
                | (.current_mode | .width, .height, .refresh, .picture_aspect_ratio) ,
                (.modes | length , (.[] | .width, .height, .refresh, .picture_aspect_ratio)))")
}

## Pick options ---

pick_output() {
	choice_output=$(fuzzy_picker "$(list_outputs_with_alias)" "Output" | awk '{print $1}')
}

pick_operation() {
	choice_operation=$(fuzzy_picker "$(list_operations)" "Operations")
}

pick_scale_factor() {
	choice_scale_factor=$(fuzzy_picker "$(list_scale_factor)" "Scale factor")
}

pick_rotation() {
	choice_rotation=$(fuzzy_picker "$(list_rotations)" "Rotation options")
}

pick_mode() {
	# Removes the aspect ratio and duplicates for now
	modes=$(list_modes | awk '{print $1}' | uniq)
	choice_mode=$(fuzzy_picker "$modes" "Modes")
}

## Run operations ---

operation_scale() {
	swaymsg output "$choice_output" scale "$choice_scale_factor"
}

operation_toggle() {
	swaymsg output "$choice_output" toggle
}

operation_mode() {
	swaymsg output "$choice_output" mode "$choice_mode"
}

operation_rotation() {
	swaymsg output "$choice_output" transform "$choice_rotation"
}

run_operation() {
	case "$choice_operation" in
	Scale)
		pick_output
		pick_scale_factor
		operation_scale
		;;
	Toggle)
		pick_output
		operation_toggle
		;;
	Mode)
		pick_output
		pick_mode
		operation_mode
		;;
	Rotate)
		pick_output
		pick_rotation
		operation_rotation
		;;
	List)
		list_outputs_info
		;;
	esac
}

## Script general ---

fuzzy_picker() {
	echo "$1" | fzf \
		--border=sharp \
		--cycle \
		--header="$2" \
		--header-first \
		--info=inline \
		--margin=0,0,0,0 \
		--padding=0,0,0,1 \
		--height=50%
}

print_help() {
	printf "\
> Sway output control <
Options:
    -h, --help                       Show this help.
    -l, --list                       List outputs information.
    -m, --mode <alias> <mode>        Change the output mode.
    -r, --rotate <alias> <rotation>  Rotate an output.
    -s, --scale <alias> <scale>      Scale an output.
    -t, --toggle <alias>             Toggle and output.

Info:
    Operations and options have a fuzzy selector if not specified.
    See 'man 5 sway-output' for more documentation.
"
}

parse_command() {
	case $# in
	"0") # No flags
		pick_operation
		run_operation
		;;
	"1") # With operation flag
		case "$1" in
		-s | --scale)
			choice_operation="Scale"
			run_operation
			;;
		-t | --toggle)
			choice_operation="Toggle"
			run_operation
			;;
		-m | --mode)
			choice_operation="Mode"
			run_operation
			;;
		-r | --rotate)
			choice_operation="Rotate"
			run_operation
			;;
		-l | --list)
			list_outputs_info
			;;
		-h | --help | *)
			print_help
			;;
		esac
		;;
	"2") # With operation flag + output information
		case "$1" in
		-s | --scale)
			choice_output=$(get_output_from_alias "$2")
			pick_scale_factor
			operation_scale
			;;
		-t | --toggle)
			choice_output=$(get_output_from_alias "$2")
			operation_toggle
			;;
		-m | --mode)
			choice_output=$(get_output_from_alias "$2")
			pick_mode
			operation_mode
			;;
		-r | --rotate)
			choice_output=$(get_output_from_alias "$2")
			pick_rotation
			operation_rotation
			;;
		*)
			print_help
			;;
		esac
		;;
	"3") # With operation flag + output information + additional information
		case "$1" in
		-s | --scale)
			choice_output=$(get_output_from_alias "$2")
			choice_scale_factor="$3"
			operation_scale
			;;
		-m | --mode)
			choice_output=$(get_output_from_alias "$2")
			choice_mode="$3"
			operation_mode
			;;
        -r | --rotate)
			choice_output=$(get_output_from_alias "$2")
            choice_rotation="$3"
			operation_rotation
            ;;
		*)
			print_help
			;;
		esac
		;;
	*)
		print_help
		;;
	esac
}

parse_command "$@"
